modLoader = "kotlinforforge"
loaderVersion = "[3.9,)"
license = "LGPL-3.0"
[[mods]]
modId = "ingameime"
version = "${file.jarVersion}"
displayName = "IngameIME"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
displayURL = "https://github.com/Windmill-City/IngameIME-Minecraft"
logoFile = "icon.png"
authors = "Windmill_City"
description = '''
Enable IME in FullScreen Minecraft
'''
[[dependencies.ingameime]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.ingameime]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.ingameime]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "CLIENT"
